import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  en: {
    officialService: 'Official Life Location Code Service',
    ministry: 'Ministry of Public Administration, Home Affairs, Provincial Councils & Local Government',
    division: 'Home Affairs Division',
    nationalService: 'National Administrative Data Service',
    lifeLocationCode: 'Life Location Code',
    home: 'Home',
    locationDirectoryNav: 'Location Directory',
    locationSearch: 'Location Code Search',
    gnAnalysis: 'GN Division Analysis',
    aboutService: 'About the Service',
    dashboard: 'Dashboard',
    verification: 'DS Verification',
    reports: 'Reports',
    apiLogs: 'API Access Logs',
    officerLogin: 'Officer Login',
    signOut: 'Sign out',
    menu: 'Menu',
    governmentSriLanka: 'Government of Sri Lanka',
    officialReference: 'Official administrative location reference service',
    nationalDirectory: 'National Location Directory',
    findAccurate: 'Find accurate administrative location information',
    homeDescription: 'Search Sri Lanka’s official administrative hierarchy from province level through to Grama Niladhari divisions and villages.',
    searchCodes: 'Search location codes',
    viewAnalysis: 'View GN division analysis',
    hierarchy: 'Administrative hierarchy',
    province: 'Province',
    district: 'District',
    ds: 'Divisional Secretariat',
    gn: 'GN Division',
    village: 'Village',
    locationServiceTitle: 'Location Code Search',
    locationServiceDesc: 'Browse and search the national location code directory using cascading administrative filters.',
    openService: 'Open service',
    analysisTitle: 'GN Division Analysis',
    analysisDesc: 'Review GN division names that occur under different Divisional Secretariats.',
    officerPortal: 'Authorised Officer Portal',
    officerPortalDesc: 'Secure access for officers responsible for verification and maintenance of location records.',
    publicService: 'Public information service',
    noAccount: 'No account is required to search location codes. Login access is limited to authorised government officers.',
    footerTitle: 'Life Location Code Management System',
    footerDivision: 'Home Affairs Division, Sri Lanka',
    developedBy: 'Developed by IT Unit — Home Affairs Division',
    rights: '© 2026 All rights reserved',
    browseTitle: 'Browse Life Location Codes',
    browseDesc: 'Search or browse Sri Lanka’s administrative location directory.',
    searchByName: 'Search by village or location name',
    searchPlaceholder: 'Enter a village, GN division, or location name',
    searchDirectory: 'Search directory',
    browseArea: 'or browse by administrative area',
    selectProvince: 'Select a province',
    selectDistrict: 'Select a district',
    selectDs: 'Select a divisional secretariat',
    selectGn: 'Select a GN division',
    selectVillage: 'Select a village',
    viewRecords: 'View location records',
    clear: 'Clear selections',
    searchResults: 'Search results',
    searching: 'Searching directory…',
    recordsFound: '{count} location records found',
    downloadExcel: 'Download Excel',
    downloadPdf: 'Download PDF',
    securePortal: 'Secure officer portal',
    signInTitle: 'Sign in to LLCMS',
    authorisedOnly: 'For authorised Home Affairs Division personnel only.',
    email: 'Official email address',
    password: 'Password',
    signingIn: 'Signing in…',
    signIn: 'Sign in securely',
    accessHelp: 'Access assistance',
    accessHelpText: 'Contact your system administrator if your account has not been issued or activated.',
    returnPublic: '← Return to public service',
    loginError: 'The email address or password is incorrect.',
    loadingRecords: 'Loading records…',
    noData: 'No data found.',
    backToDistrictMap: 'Back to district map',
    resetSelection: 'Reset selection',
    locationBrowser: 'Administrative location browser',
    districtMapAll: 'Sri Lanka District Map',
    districtMapSelected: '{province} District Map',
    locationBrowserDescription: 'Explore provinces and navigate through districts, divisional secretariats, and GN divisions.',
    searchArea: 'Search {area}',
    noDistricts: 'No districts loaded.',
    selectDistrictFirst: 'Select a district first.',
    noDsDivisions: 'No DS divisions found.',
    selectDsFirst: 'Select a DS division first.',
    noGnDivisions: 'No GN divisions found.',
    noMatchingRecords: 'No matching records.',
  },
  si: {
    officialService: 'නිල ලයිෆ් ස්ථාන කේත සේවාව',
    ministry: 'රාජ්‍ය පරිපාලන, ස්වදේශ කටයුතු, පළාත් සභා හා පළාත් පාලන අමාත්‍යාංශය',
    division: 'ස්වදේශ කටයුතු අංශය',
    nationalService: 'ජාතික පරිපාලන දත්ත සේවාව',
    lifeLocationCode: 'ලයිෆ් ස්ථාන කේතය',
    home: 'මුල් පිටුව',
    locationDirectoryNav: 'ස්ථාන නාමාවලිය',
    locationSearch: 'ස්ථාන කේත සෙවීම',
    gnAnalysis: 'ග්‍රාම නිලධාරී වසම් විශ්ලේෂණය',
    aboutService: 'සේවාව පිළිබඳ',
    dashboard: 'පාලක පුවරුව',
    verification: 'ප්‍රාදේශීය ලේකම් සත්‍යාපනය',
    reports: 'වාර්තා',
    apiLogs: 'API ප්‍රවේශ සටහන්',
    officerLogin: 'නිලධාරී පිවිසුම',
    signOut: 'පිටවීම',
    menu: 'මෙනුව',
    governmentSriLanka: 'ශ්‍රී ලංකා රජය',
    officialReference: 'නිල පරිපාලන ස්ථාන යොමු සේවාව',
    nationalDirectory: 'ජාතික ස්ථාන නාමාවලිය',
    findAccurate: 'නිවැරදි පරිපාලන ස්ථාන තොරතුරු සොයන්න',
    homeDescription: 'පළාතේ සිට ග්‍රාම නිලධාරී වසම් සහ ගම්මාන දක්වා ශ්‍රී ලංකාවේ නිල පරිපාලන ධුරාවලිය සොයන්න.',
    searchCodes: 'ස්ථාන කේත සොයන්න',
    viewAnalysis: 'වසම් විශ්ලේෂණය බලන්න',
    hierarchy: 'පරිපාලන ධුරාවලිය',
    province: 'පළාත',
    district: 'දිස්ත්‍රික්කය',
    ds: 'ප්‍රාදේශීය ලේකම් කොට්ඨාසය',
    gn: 'ග්‍රාම නිලධාරී වසම',
    village: 'ගම',
    locationServiceTitle: 'ස්ථාන කේත සෙවීම',
    locationServiceDesc: 'පරිපාලන පෙරහන් භාවිතයෙන් ජාතික ස්ථාන කේත නාමාවලිය සොයන්න.',
    openService: 'සේවාව විවෘත කරන්න',
    analysisTitle: 'ග්‍රාම නිලධාරී වසම් විශ්ලේෂණය',
    analysisDesc: 'විවිධ ප්‍රාදේශීය ලේකම් කොට්ඨාස යටතේ ඇති සමාන වසම් නම් පරීක්ෂා කරන්න.',
    officerPortal: 'බලයලත් නිලධාරී ද්වාරය',
    officerPortalDesc: 'ස්ථාන වාර්තා සත්‍යාපනය සහ නඩත්තුව සඳහා ආරක්ෂිත ප්‍රවේශය.',
    publicService: 'මහජන තොරතුරු සේවාව',
    noAccount: 'ස්ථාන කේත සෙවීමට ගිණුමක් අවශ්‍ය නොවේ. පිවිසුම බලයලත් රජයේ නිලධාරීන්ට පමණි.',
    footerTitle: 'ලයිෆ් ස්ථාන කේත කළමනාකරණ පද්ධතිය',
    footerDivision: 'ස්වදේශ කටයුතු අංශය, ශ්‍රී ලංකාව',
    developedBy: 'ස්වදේශ කටයුතු අංශයේ තොරතුරු තාක්ෂණ ඒකකය විසින් සංවර්ධනය කරන ලදී',
    rights: '© 2026 සියලු හිමිකම් ඇවිරිණි',
    browseTitle: 'ලයිෆ් ස්ථාන කේත පිරික්සන්න',
    browseDesc: 'ශ්‍රී ලංකාවේ පරිපාලන ස්ථාන නාමාවලිය සොයන්න හෝ පිරික්සන්න.',
    searchByName: 'ගම හෝ ස්ථානයේ නම අනුව සොයන්න',
    searchPlaceholder: 'ගමක්, වසමක් හෝ ස්ථානයක් ඇතුළත් කරන්න',
    searchDirectory: 'නාමාවලිය සොයන්න',
    browseArea: 'හෝ පරිපාලන ප්‍රදේශය අනුව පිරික්සන්න',
    selectProvince: 'පළාතක් තෝරන්න',
    selectDistrict: 'දිස්ත්‍රික්කයක් තෝරන්න',
    selectDs: 'ප්‍රාදේශීය ලේකම් කොට්ඨාසයක් තෝරන්න',
    selectGn: 'ග්‍රාම නිලධාරී වසමක් තෝරන්න',
    selectVillage: 'ගමක් තෝරන්න',
    viewRecords: 'ස්ථාන වාර්තා බලන්න',
    clear: 'තේරීම් ඉවත් කරන්න',
    searchResults: 'සෙවුම් ප්‍රතිඵල',
    searching: 'නාමාවලිය සොයමින්…',
    recordsFound: 'ස්ථාන වාර්තා {count}ක් හමු විය',
    downloadExcel: 'Excel බාගන්න',
    downloadPdf: 'PDF බාගන්න',
    securePortal: 'ආරක්ෂිත නිලධාරී ද්වාරය',
    signInTitle: 'LLCMS වෙත පිවිසෙන්න',
    authorisedOnly: 'බලයලත් ස්වදේශ කටයුතු අංශයේ නිලධාරීන් සඳහා පමණි.',
    email: 'නිල විද්‍යුත් තැපැල් ලිපිනය',
    password: 'මුරපදය',
    signingIn: 'පිවිසෙමින්…',
    signIn: 'ආරක්ෂිතව පිවිසෙන්න',
    accessHelp: 'ප්‍රවේශ සහාය',
    accessHelpText: 'ඔබට ගිණුමක් නිකුත් කර හෝ සක්‍රිය කර නොමැති නම් පද්ධති පරිපාලක අමතන්න.',
    returnPublic: '← මහජන සේවාව වෙත ආපසු',
    loginError: 'විද්‍යුත් තැපැල් ලිපිනය හෝ මුරපදය වැරදිය.',
    loadingRecords: 'වාර්තා පූරණය වෙමින්…',
    noData: 'දත්ත හමු නොවීය.',
    backToDistrictMap: 'දිස්ත්‍රික් සිතියමට ආපසු',
    resetSelection: 'තේරීම යළි සකසන්න',
    locationBrowser: 'පරිපාලන ස්ථාන ගවේෂකය',
    districtMapAll: 'ශ්‍රී ලංකා දිස්ත්‍රික් සිතියම',
    districtMapSelected: '{province} දිස්ත්‍රික් සිතියම',
    locationBrowserDescription: 'පළාත්, දිස්ත්‍රික්ක, ප්‍රාදේශීය ලේකම් කොට්ඨාස සහ ග්‍රාම නිලධාරී වසම් හරහා ගවේෂණය කරන්න.',
    searchArea: '{area} සොයන්න',
    noDistricts: 'දිස්ත්‍රික්ක පූරණය වී නොමැත.',
    selectDistrictFirst: 'පළමුව දිස්ත්‍රික්කයක් තෝරන්න.',
    noDsDivisions: 'ප්‍රාදේශීය ලේකම් කොට්ඨාස හමු නොවීය.',
    selectDsFirst: 'පළමුව ප්‍රාදේශීය ලේකම් කොට්ඨාසයක් තෝරන්න.',
    noGnDivisions: 'ග්‍රාම නිලධාරී වසම් හමු නොවීය.',
    noMatchingRecords: 'ගැළපෙන වාර්තා නොමැත.',
  },
  ta: {
    officialService: 'அதிகாரப்பூர்வ லைஃப் இருப்பிடக் குறியீட்டு சேவை',
    ministry: 'பொது நிர்வாக, உள்நாட்டலுவல்கள், மாகாண சபைகள் மற்றும் உள்ளூராட்சி அமைச்சு',
    division: 'உள்நாட்டலுவல்கள் பிரிவு',
    nationalService: 'தேசிய நிர்வாகத் தரவுச் சேவை',
    lifeLocationCode: 'லைஃப் இருப்பிடக் குறியீடு',
    home: 'முகப்பு',
    locationDirectoryNav: 'இருப்பிடப் பட்டியல்',
    locationSearch: 'இருப்பிடக் குறியீடு தேடல்',
    gnAnalysis: 'கிராம அலுவலர் பிரிவு பகுப்பாய்வு',
    aboutService: 'சேவை பற்றி',
    dashboard: 'கட்டுப்பாட்டுப் பலகை',
    verification: 'பிரதேச செயலக சரிபார்ப்பு',
    reports: 'அறிக்கைகள்',
    apiLogs: 'API அணுகல் பதிவுகள்',
    officerLogin: 'அலுவலர் உள்நுழைவு',
    signOut: 'வெளியேறு',
    menu: 'பட்டியல்',
    governmentSriLanka: 'இலங்கை அரசு',
    officialReference: 'அதிகாரப்பூர்வ நிர்வாக இருப்பிட குறிப்புச் சேவை',
    nationalDirectory: 'தேசிய இருப்பிடப் பட்டியல்',
    findAccurate: 'துல்லியமான நிர்வாக இருப்பிடத் தகவல்களைக் கண்டறியுங்கள்',
    homeDescription: 'மாகாணம் முதல் கிராம அலுவலர் பிரிவுகள் மற்றும் கிராமங்கள் வரை இலங்கையின் அதிகாரப்பூர்வ நிர்வாக அமைப்பைத் தேடுங்கள்.',
    searchCodes: 'இருப்பிடக் குறியீடுகளைத் தேடுங்கள்',
    viewAnalysis: 'பிரிவு பகுப்பாய்வைப் பார்க்கவும்',
    hierarchy: 'நிர்வாகப் படிநிலை',
    province: 'மாகாணம்',
    district: 'மாவட்டம்',
    ds: 'பிரதேச செயலகம்',
    gn: 'கிராம அலுவலர் பிரிவு',
    village: 'கிராமம்',
    locationServiceTitle: 'இருப்பிடக் குறியீடு தேடல்',
    locationServiceDesc: 'நிர்வாக வடிகட்டிகளைப் பயன்படுத்தி தேசிய இருப்பிடக் குறியீட்டுப் பட்டியலைத் தேடுங்கள்.',
    openService: 'சேவையைத் திறக்கவும்',
    analysisTitle: 'கிராம அலுவலர் பிரிவு பகுப்பாய்வு',
    analysisDesc: 'வெவ்வேறு பிரதேச செயலகங்களின் கீழ் காணப்படும் ஒரே பெயருள்ள பிரிவுகளைப் பார்வையிடுங்கள்.',
    officerPortal: 'அங்கீகரிக்கப்பட்ட அலுவலர் தளம்',
    officerPortalDesc: 'இருப்பிடப் பதிவுகளைச் சரிபார்த்து பராமரிக்கும் அலுவலர்களுக்கான பாதுகாப்பான அணுகல்.',
    publicService: 'பொதுத் தகவல் சேவை',
    noAccount: 'இருப்பிடக் குறியீடுகளைத் தேட கணக்கு தேவையில்லை. உள்நுழைவு அங்கீகரிக்கப்பட்ட அரசு அலுவலர்களுக்கு மட்டுமே.',
    footerTitle: 'லைஃப் இருப்பிடக் குறியீட்டு முகாமைத்துவ அமைப்பு',
    footerDivision: 'உள்நாட்டலுவல்கள் பிரிவு, இலங்கை',
    developedBy: 'உள்நாட்டலுவல்கள் பிரிவு தகவல் தொழில்நுட்ப அலகால் உருவாக்கப்பட்டது',
    rights: '© 2026 அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
    browseTitle: 'லைஃப் இருப்பிடக் குறியீடுகளை உலாவுங்கள்',
    browseDesc: 'இலங்கையின் நிர்வாக இருப்பிடப் பட்டியலைத் தேடுங்கள் அல்லது உலாவுங்கள்.',
    searchByName: 'கிராமம் அல்லது இருப்பிடப் பெயரால் தேடுங்கள்',
    searchPlaceholder: 'கிராமம், கிராம அலுவலர் பிரிவு அல்லது இருப்பிடத்தை உள்ளிடுங்கள்',
    searchDirectory: 'பட்டியலைத் தேடுங்கள்',
    browseArea: 'அல்லது நிர்வாகப் பகுதியின்படி உலாவுங்கள்',
    selectProvince: 'மாகாணத்தைத் தேர்ந்தெடுக்கவும்',
    selectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    selectDs: 'பிரதேச செயலகத்தைத் தேர்ந்தெடுக்கவும்',
    selectGn: 'கிராம அலுவலர் பிரிவைத் தேர்ந்தெடுக்கவும்',
    selectVillage: 'கிராமத்தைத் தேர்ந்தெடுக்கவும்',
    viewRecords: 'இருப்பிடப் பதிவுகளைப் பார்க்கவும்',
    clear: 'தேர்வுகளை அழிக்கவும்',
    searchResults: 'தேடல் முடிவுகள்',
    searching: 'பட்டியல் தேடப்படுகிறது…',
    recordsFound: '{count} இருப்பிடப் பதிவுகள் கிடைத்தன',
    downloadExcel: 'Excel பதிவிறக்கம்',
    downloadPdf: 'PDF பதிவிறக்கம்',
    securePortal: 'பாதுகாப்பான அலுவலர் தளம்',
    signInTitle: 'LLCMS இல் உள்நுழைக',
    authorisedOnly: 'அங்கீகரிக்கப்பட்ட உள்நாட்டலுவல்கள் பிரிவு பணியாளர்களுக்கு மட்டுமே.',
    email: 'அதிகாரப்பூர்வ மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    signingIn: 'உள்நுழைகிறது…',
    signIn: 'பாதுகாப்பாக உள்நுழைக',
    accessHelp: 'அணுகல் உதவி',
    accessHelpText: 'உங்கள் கணக்கு வழங்கப்படவில்லை அல்லது செயல்படுத்தப்படவில்லை என்றால் கணினி நிர்வாகியைத் தொடர்புகொள்ளவும்.',
    returnPublic: '← பொதுச் சேவைக்குத் திரும்புக',
    loginError: 'மின்னஞ்சல் முகவரி அல்லது கடவுச்சொல் தவறானது.',
    loadingRecords: 'பதிவுகள் ஏற்றப்படுகின்றன…',
    noData: 'தரவு எதுவும் கிடைக்கவில்லை.',
    backToDistrictMap: 'மாவட்ட வரைபடத்திற்குத் திரும்பு',
    resetSelection: 'தேர்வை மீட்டமை',
    locationBrowser: 'நிர்வாக இட உலாவி',
    districtMapAll: 'இலங்கை மாவட்ட வரைபடம்',
    districtMapSelected: '{province} மாவட்ட வரைபடம்',
    locationBrowserDescription: 'மாகாணங்கள், மாவட்டங்கள், பிரதேச செயலகங்கள் மற்றும் கிராம அலுவலர் பிரிவுகள் வழியாக ஆராயுங்கள்.',
    searchArea: '{area} தேடுக',
    noDistricts: 'மாவட்டங்கள் ஏற்றப்படவில்லை.',
    selectDistrictFirst: 'முதலில் ஒரு மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.',
    noDsDivisions: 'பிரதேச செயலகங்கள் எதுவும் கிடைக்கவில்லை.',
    selectDsFirst: 'முதலில் ஒரு பிரதேச செயலகத்தைத் தேர்ந்தெடுக்கவும்.',
    noGnDivisions: 'கிராம அலுவலர் பிரிவுகள் எதுவும் கிடைக்கவில்லை.',
    noMatchingRecords: 'பொருந்தும் பதிவுகள் இல்லை.',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('llcms_language') || 'en')

  useEffect(() => {
    localStorage.setItem('llcms_language', language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key, vars = {}) => {
      let text = translations[language]?.[key] || translations.en[key] || key
      Object.entries(vars).forEach(([name, value]) => { text = text.replace(`{${name}}`, value) })
      return text
    },
    localizedName: item => item?.[`name_${language === 'si' ? 'sinhala' : language === 'ta' ? 'tamil' : 'english'}`] || item?.name_english || '',
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
